package com.anfly.bigfly.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.anfly.bigfly.distance.bean.NewsDbBean;

import com.anfly.bigfly.dao.NewsDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsDbBeanDaoConfig;

    private final NewsDbBeanDao newsDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsDbBeanDaoConfig = daoConfigMap.get(NewsDbBeanDao.class).clone();
        newsDbBeanDaoConfig.initIdentityScope(type);

        newsDbBeanDao = new NewsDbBeanDao(newsDbBeanDaoConfig, this);

        registerDao(NewsDbBean.class, newsDbBeanDao);
    }
    
    public void clear() {
        newsDbBeanDaoConfig.clearIdentityScope();
    }

    public NewsDbBeanDao getNewsDbBeanDao() {
        return newsDbBeanDao;
    }

}
